services:
    Shopping\ApiTKUrlBundle\Service\ApiService:
        public: true
        arguments:
            - '@request_stack'
            - '@Shopping\ApiTKHeaderBundle\Service\HeaderInformation'

    Shopping\ApiTKUrlBundle\EventListener\AnnotationListener:
        public: false
        arguments:
            - '@annotations.reader'
            - '@Shopping\ApiTKUrlBundle\Service\ApiService'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiTKUrlBundle\Describer\AnnotationDescriber:
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@Shopping\ApiTKCommonBundle\Util\ControllerReflector'
            - '@annotations.reader'
        tags:
            - { name: 'nelmio_api_doc.route_describer', priority: -2000 }

    Shopping\ApiTKUrlBundle\ParamConverter\ResultConverter:
        arguments:
            - '@?doctrine'
            - '@Shopping\ApiTKUrlBundle\Service\ApiService'
        tags:
            - { name: request.param_converter }
